// http://nodejs.org/api/globals.html
var global;
var process;
var console;
function Buffer(){}
function require(){}
var __filename;
var __dirname;
var module;
var exports;
function setTimeout(){}
function clearTimeout(){}
function setInterval(){}
function clearInterval(){}
