#!/usr/bin/env node

var path = require('path');
var fs   = require('fs');

var pkg  = path.join(path.dirname(fs.realpathSync(__filename)), '../');

var cljs = require(pkg);

var options = { path: ( pkg + 'support/cljs/postinstall_build.cljs' ) };
var outputDir = pkg + 'support/out';
var cljscOptions = '{:optimizations :simple :target :nodejs :pretty-print false :output-dir "' + outputDir + '"}';
var javaOptions = null;

try {
  cljs.build(options, cljscOptions, javaOptions);
} catch (error) {
  process.stdout.write('\nError: ' + error.message + '\n');
  process.exit(1);
}
